//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pull_Tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Out_SingleFile {
            get {
                return ((bool)(this["Out_SingleFile"]));
            }
            set {
                this["Out_SingleFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Out_WriteStatus {
            get {
                return ((bool)(this["Out_WriteStatus"]));
            }
            set {
                this["Out_WriteStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pre_FilterUnreliable {
            get {
                return ((bool)(this["Pre_FilterUnreliable"]));
            }
            set {
                this["Pre_FilterUnreliable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Out_ZipResults {
            get {
                return ((bool)(this["Out_ZipResults"]));
            }
            set {
                this["Out_ZipResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Pull_Mode {
            get {
                return ((int)(this["Pull_Mode"]));
            }
            set {
                this["Pull_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public string Pull_ModeInterval {
            get {
                return ((string)(this["Pull_ModeInterval"]));
            }
            set {
                this["Pull_ModeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public decimal Pull_TimeoutPeriod {
            get {
                return ((decimal)(this["Pull_TimeoutPeriod"]));
            }
            set {
                this["Pull_TimeoutPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Pull_MaxThreads {
            get {
                return ((decimal)(this["Pull_MaxThreads"]));
            }
            set {
                this["Pull_MaxThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Out_UTCTime {
            get {
                return ((bool)(this["Out_UTCTime"]));
            }
            set {
                this["Out_UTCTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Pull_BatchingInterval {
            get {
                return ((decimal)(this["Pull_BatchingInterval"]));
            }
            set {
                this["Pull_BatchingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Out_Directory {
            get {
                return ((string)(this["Out_Directory"]));
            }
            set {
                this["Out_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Metrics_Perform {
            get {
                return ((bool)(this["Metrics_Perform"]));
            }
            set {
                this["Metrics_Perform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public decimal Metrics_AnalysisWindow {
            get {
                return ((decimal)(this["Metrics_AnalysisWindow"]));
            }
            set {
                this["Metrics_AnalysisWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Metrics_CalcMean {
            get {
                return ((bool)(this["Metrics_CalcMean"]));
            }
            set {
                this["Metrics_CalcMean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Metrics_CalcMax {
            get {
                return ((bool)(this["Metrics_CalcMax"]));
            }
            set {
                this["Metrics_CalcMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Metrics_CalcMin {
            get {
                return ((bool)(this["Metrics_CalcMin"]));
            }
            set {
                this["Metrics_CalcMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Metrics_CalcLinear {
            get {
                return ((bool)(this["Metrics_CalcLinear"]));
            }
            set {
                this["Metrics_CalcLinear"] = value;
            }
        }
    }
}
